= KIWI Documentation Version 7

This is the source for the official KIWI documentation for version 7.
If you are searching for version 8 and later, refer to
https://github.com/suse/kiwi.

Released versions of the KIWI documentation are published at
https://www.suse.com/documentation/.


== Branches

.Overview of important branches
[options="header"]
|================================================
| Name             | Purpose
| `develop`        | doc development (latest development version)
| `maintenance/*`  | maintenance for released versions (n/a)
| `trans/*`        | translations for released versions (n/a)
| `master`         | latest released version
|================================================


== Contributing

If you would like to contribute, please fork this repository and send
pull requests. Always use the `develop` branch for your edits! +
Contributors with direct access to the repository are encouraged to use the
GitFlow-avh workflow (package `git-flow-avh`). However, this is not a must.
For help on style and structure, refer to the https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/[Documentation Styleguide] 


.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.

== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html.
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** Learn more at https://opensuse.github.io/daps
